title: ""
description: ""
keywords: ""

facebook_username: ""
instagram_username: ""

# Build settings
markdown: kramdown

theme: minima

plugins:
  - jekyll-feed

permalink: /:title/

# -------> Dev Configs

# LOCAL
baseurl: ""
url: "http://localhost:3000/" # Colocar o dominio online

# ICLOUDS SERVER
# baseurl: "/espacomais" # dominio iclouds
# url: "http://servidor.iclouds.com.br/espacomais" # Colocar o dominio iclouds
# atendimento-email: "suporte@iclouds.com.br" #Testes com envio de email


