title: ""
description: ""
keywords: ""

facebook_username: ""
instagram_username: ""

# Build settings
markdown: kramdown

theme: minima

plugins:
  - jekyll-feed

permalink: /:title/

# -------> Dev Configs

# LOCAL
baseurl: ""
url: "http://localhost:3000/" # Colocar o dominio online


